#!/usr/bin/env bash

#Configure Nginx so that its HTTP response contains
#a custom header (on web-01 and web-02)

hostname=ubuntu@100.26.224.13
sudo sed -i 's/# server_tokens off;/server_tokens off;\n        add_header X-Served-By $hostname;/g' /etc/nginx/nginx.conf
