#!/usr/bin/env bash

#Configure Nginx so that its HTTP response contains
#a custom header (on web-01 and web-02)

hostname=ubuntu@100.26.224.13
sudo sed -i "/http {/a \        add_header X-Served-By ${hostname};" /etc/nginx/nginx.conf
