#!/usr/bin/env bash
# stop the nginx service if it's already running

# Install Nginx
apt-get update
apt-get install nginx -y

# Stop Nginx service
systemctl stop nginx.service

# Set nginx user and group
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/# server_names_hash_bucket_size/server_names_hash_bucket_size/g' /etc/nginx/nginx.conf

# Restart Nginx service
systemctl start nginx.service

# Configure Nginx to listen on all active IPs on port 8080
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx service again
systemctl restart nginx.service

