#!/usr/bin/env bash
# stop the nginx service if it's already running

# Build the Docker image with a modified nginx user
docker build -t nginx_user .

# Run the Docker container as the nginx user
docker run -d --name nginx_container -u nginx -p 80:80 nginx_user
